// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwactcwdsfkytqmsdkde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3YWN0Y3dkc2ZreXRxbXNka2RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNjM5MDIsImV4cCI6MjA2NzkzOTkwMn0.Ejwws4kG6SHSaycTJItrRbfHbSIXdlu8OLg07VXr3n8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
